name = "cors-proxy"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "cors-proxy"

# Variáveis de ambiente (podem ser sobrescritas via CLI ou dashboard)
[vars]
ENVIRONMENT = "production"

# Para desenvolvimento local
[env.development]
name = "cors-proxy-dev"
[env.development.vars]
ENVIRONMENT = "development"

# Configurações de build
[build]
command = ""

# Configurações de observabilidade
[observability]
enabled = true